### ISSUE TITLE
丢包率怎么样

### ISSUE THREAD

**Issue by zeusYi** [hcymysql/mysql_sniffer#1]
这个工具的丢包率怎么样？比如一个周期内实际做了1000条SQL，实际能抓到多少个SQL?

**Comment by hcymysql** [comment]
可以这样简单测试一下。

第一步，在A机器上开启mysql_sniffer进程监听3306端口。
```
shell> ./mysql_sniffer -p 3306 -c
```

第二步，在B机器上，执行下面的命令，循环10000次select，每次结果加1
```
shell> for i in $(seq 1 10000); do mysql -h192.168.198.239 -uadmin -phechunyang -P3306 -e "select $i"; done
```

第三步，在A机器上，看mysql_sniffer是否抓取到了1万条SQL语句，即select 10000;
